#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute

user:
    resource: ../src/User/Presentation/Http/Controller
    type: attribute
